tasks:
  - name: git
    before: |
      echo "Hello Programmer, thanks for using better." && pip install pytube && pip install --upgrade pip && git config lfs.https://github.com/manfromexistence-better/better.git/info/lfs.locksverify false
    command: |
      git status
  # - name: rust
  #   before: |
  #     cd rust
  #   init: |
  #     echo "export RUSTUP_INIT_SKIP_KEYRING=yes" >> ~/.bashrc
  #     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh && . "$HOME/.cargo/env"
  #   command: |
  #     rustc --version && cargo --version
  # - name: c++
  #   before: |
  #     cd rust
  #   init: |
  #     gcc main.cpp -o main
  #   command: |
  #     echo "C++"