repos:
- repo: local
  hooks:
  - id: linter
    name: Apply linter fixes
    entry: ruff check --fix .
    language: system
    types: [python]
    require_serial: true
  - id: format
    name: Apply formatting fixes
    entry: autopep8 --in-place .
    language: system
    types: [python]
